[sharepoint]
url = "https://365tsel-my.sharepoint.com/personal/fauzi_ramdani_telkomsel_co_id"
username = "fauzi_ramdani@telkomsel.co.id"
password = "Hanesty_6#"
folder_path = "/Documents/Telkomsel/NOP Palangkaraya/Tracker"
