[sharepoint]
url = "https://365tsel-my.sharepoint.com/personal/fauzi_ramdani_telkomsel_co_id"
username = "fauzi.ramdani@telkomsel.co.id"
password = "Hanesty_6#"
file_path = "/sites/NamaSiteLo/Shared Documents/Data_Availability.csv"
